### ISSUE TITLE
No output when upgrading nextest to 0.9.86

### ISSUE THREAD

**Issue by fredrik-jansson-se** [Canop/bacon#280]
I'm running bacon `3.6.0` with nextest `0.9.86 (046e241b1 2024-12-12)`.

Since bacon 3.6.0 I no longer see any error output from failing tests:
```
 1  failed: parser::test::var
 no output
```

Using cargo test (from bacon) I get
```
 1  failed: parser::test::var
 thread 'parser::test::var' panicked at src/parser.rs:36:79:
 called `Result::unwrap()` on an `Err` value: Error { variant: ParsingError { positives: [identifier], negativ
 es: [] }, location: Pos(3), line_col: Pos((1, 4)), path: None, line: "var a = 2;", continued_line: None, pars
 e_attempts: None }
```

Running nextest outside bacon:
```
──── STDERR:             llvm::bin/llvm parser::test::var
thread 'parser::test::var' panicked at src/parser.rs:36:79:
called `Result::unwrap()` on an `Err` value: Error { variant: ParsingError { positives: [identifier], negatives: [] }, location: Pos(3), line_col: Pos((1, 4)), path: None, line: "var a = 2;", continued_line: None, parse_attempts: None }
```

Am I missing something or is there a setting I can't find to enable output from nextest in bacon?

**Comment by Canop** [comment]
You mean the same configuration which was working before 3.6 isn't working with 3.6 ?

**Comment by fredrik-jansson-se** [comment]
Well, I don't have any custom bacon config.

**Comment by Canop** [comment]
Can you run bacon with log enabled (eg `BACON_LOG=debug bacon nextest`) then paste the content of the bacon.log file ?

**Comment by fredrik-jansson-se** [comment]
```
17:25:51.028 [INFO] cli_log::init: Starting bacon v3.6.0 with log level DEBUG
17:25:51.029 [INFO] bacon::cli: args: Args {
    help: false,
    version: false,
    prefs: false,
    summary: false,
    no_summary: false,
    wrap: false,
    no_wrap: false,
    reverse: false,
    no_reverse: false,
    help_line: false,
    no_help_line: false,
    list_jobs: false,
    offline: false,
    init: false,
    job: Some(
        ConcreteJobRef {
            name_or_alias: Name(
                "nextest",
            ),
            scope: Scope {
                tests: [],
            },
        },
    ),
    no_default_features: false,
    features: None,
    all_features: false,
    export_locations: false,
    no_export_locations: false,
    watch: None,
    project: None,
    args: [],
    additional_job_args: [],
}
17:25:51.075 [DEBUG] bacon::cli: mission context: Context {
    name: "llvm",
    nature: Cargo,
    package_directory: "/home/frja/rust/llvm",
    workspace_root: None,
    cargo_mission_location: Some(
        CargoContext {
            cargo_toml_file: "/home/frja/rust/llvm/Cargo.toml",
            ..
        },
    ),
    path_to_watch: None,
}
17:25:51.076 [INFO] bacon::conf::settings: settings: Settings {
    additional_alias_args: None,
    additional_job_args: [],
    all_features: false,
    arg_job: Some(
        ConcreteJobRef {
            name_or_alias: Name(
                "nextest",
            ),
            scope: Scope {
                tests: [],
            },
        },
    ),
    config_files: [],
    default_job: ConcreteJobRef {
        name_or_alias: Name(
            "check",
        ),
        scope: Scope {
            tests: [],
        },
    },
    default_watch: true,
    exports: ExportsSettings {
        exports: {},
    },
    features: None,
    grace_period: Period {
        duration: 5ms,
    },
    help_line: true,
    ignore: [],
    ignored_lines: None,
    jobs: {
        "ex": Job {
            allow_failures: false,
            allow_warnings: true,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "run",
                "--example",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: true,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "run": Job {
            allow_failures: false,
            allow_warnings: true,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "run",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: true,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "doc-open": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "doc",
                "--no-deps",
                "--open",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: false,
            on_change_strategy: None,
            on_success: Some(
                Internal(
                    Back,
                ),
            ),
            watch: None,
        },
        "doc": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "doc",
                "--no-deps",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: false,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "check-all": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "check",
                "--all-targets",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: false,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "nextest": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: Some(
                Nextest,
            ),
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "nextest",
                "run",
                "--hide-progress-bar",
                "--failure-output",
                "final",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: true,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "clippy": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "clippy",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: false,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "run-long": Job {
            allow_failures: false,
            allow_warnings: true,
            analyzer: None,
            apply_gitignore: None,
            background: false,
            command: [
                "cargo",
                "run",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: true,
            on_change_strategy: Some(
                KillThenRestart,
            ),
            on_success: None,
            watch: None,
        },
        "test": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "test",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: true,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "clippy-all": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "clippy",
                "--all-targets",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: false,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
        "check": Job {
            allow_failures: false,
            allow_warnings: false,
            analyzer: None,
            apply_gitignore: None,
            background: true,
            command: [
                "cargo",
                "check",
            ],
            default_watch: None,
            env: {},
            expand_env_vars: true,
            extraneous_args: true,
            ignore: [],
            ignored_lines: None,
            kill: None,
            need_stdout: false,
            on_change_strategy: None,
            on_success: None,
            watch: None,
        },
    },
    keybindings: KeyBindings {
        F5: "refresh",
        Esc: "back",
        PageDown: "scroll-pages(1)",
        d: "job:doc-open",
        r: "job:run",
        Ctrl-q: "quit",
        s: "toggle-summary",
        ?: "help",
        p: "toggle-pause",
        b: "toggle-backtrace(1)",
        Down: "scroll-lines(1)",
        i: "job:initial",
        w: "toggle-wrap",
        Home: "scroll-to-top",
        q: "quit",
        Ctrl-d: "job:default",
        a: "job:check-all",
        f: "scope-to-failures",
        Ctrl-c: "quit",
        c: "job:clippy-all",
        Space: "scroll-pages(.8)",
        n: "job:nextest",
        t: "job:test",
        PageUp: "scroll-pages(-1)",
        h: "help",
        Up: "scroll-lines(-1)",
        End: "scroll-to-bottom",
    },
    no_default_features: false,
    on_change_strategy: None,
    reverse: false,
    show_changes_count: false,
    summary: false,
    watch: [],
    wrap: true,
    env: {
        "CARGO_TERM_COLOR": "always",
    },
}
17:25:51.083 [DEBUG] bacon::jobs::job_stack: picking job Initial
17:25:51.083 [DEBUG] bacon::context: watches: ["src", "tests", "benches", "examples", "build.rs"]
17:25:51.084 [INFO] bacon::app: mission.ignorer() took 183.884µs
17:25:51.084 [DEBUG] bacon::watcher: add watch dir "/home/frja/rust/llvm/src"
17:25:51.084 [DEBUG] bacon::watcher: add watch file "/home/frja/rust/llvm/Cargo.toml"
17:25:51.084 [DEBUG] bacon::mission: command builder: CommandBuilder {
    exe: "cargo",
    current_dir: Some(
        "/home/frja/rust/llvm",
    ),
    args: [
        "nextest",
        "run",
        "--hide-progress-bar",
        "--failure-output",
        "final",
    ],
    with_stdout: true,
    envs: {
        "CARGO_TERM_COLOR": "always",
    },
}
17:25:51.084 [INFO] bacon::exec::executor: start task Task { backtrace: None, grace_period: Period { duration: 5ms } }
17:25:51.153 [DEBUG] bacon::watcher: ignoring access event: Event { kind: Access(Open(Any)), paths: ["/home/frja/rust/llvm/Cargo.toml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
17:25:51.176 [DEBUG] bacon::watcher: ignoring access event: Event { kind: Access(Open(Any)), paths: ["/home/frja/rust/llvm/Cargo.toml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
17:25:51.202 [INFO] bacon::app: execution finished with status: Some(ExitStatus(unix_wait_status(25600)))
17:25:51.203 [DEBUG] bacon::analysis::standard::standard_report_building: stats: Stats {
    warnings: 1,
    errors: 0,
    test_fails: 1,
    passed_tests: 5,
    location_lines: 1,
    normal_lines: 7,
}
17:25:51.204 [DEBUG] bacon::result::command_result: report stats: Stats { warnings: 1, errors: 0, test_fails: 1, passed_tests: 5, location_lines: 1, normal_lines: 7 }
17:25:51.204 [DEBUG] bacon::state: Got report
17:25:51.204 [INFO] bacon::state: Stats: Stats {
    warnings: 1,
    errors: 0,
    test_fails: 1,
    passed_tests: 5,
    location_lines: 1,
    normal_lines: 7,
}
17:25:51.204 [DEBUG] bacon::result::wrapped_report: wrapping report
17:25:52.938 [DEBUG] bacon::app: key combination pressed: q
17:25:52.938 [DEBUG] bacon::app: requested action: Internal(Quit)
17:25:52.939 [DEBUG] bacon::exec::executor: failed to send 'die' signal: sending on a disconnected channel
17:25:52.939 [INFO] bacon: bye
```

**Comment by Canop** [comment]
Sorry for the log, it's not needed.

I updated cargo nextest to the last version and I can reproduce your problem. They changed the output :\

**Comment by fredrik-jansson-se** [comment]
Got it, thanks for all help (again)!!

**Comment by Canop** [comment]
If their format isn't stabilized, the analyzer should probably be modified to use their JSON output.

If anybody's willing to dive into this, they're welcome.

**Comment by fredrik-jansson-se** [comment]
I can't make any promises, but sounds like a good challenge for the upcoming Holidays for me :)

**Comment by Canop** [comment]
If you try this, and you have questions, you're welcome to come and chat on [Miaou](https://miaou.dystroy.org/4683).

Two approaches seem possible: either make a new version of [the existing nextest analyzer](https://github.com/Canop/bacon/tree/main/src/analysis/nextest), or make a new nextest_json analyser or libtest_analyzer, similar to [the cargo_json analyzer](https://github.com/Canop/bacon/blob/main/src/analysis/cargo_json/mod.rs), to be used with `cargo nextest run --message-format libtest-json` (this would imply there's enough data in that JSON output, I didn't check).

**Comment by Canop** [comment]
Or your browser has an extension or a setting which breaks Miaou, probably.

**Comment by sunshowers** [comment]
Hi there, creator of nextest here.

> I updated cargo nextest to the last version and I can reproduce your problem. They changed the output :\

Sorry about that! The output format is explicitly [not part of the stable guarantees](https://nexte.st/docs/stability/) -- I don't want to make too many tweaks to it, but there will likely be a few here and there.

The [libtest-json format is functional](https://nexte.st/docs/machine-readable/libtest-json/) but not quite full-fidelity, because cargo test doesn't support many of the features that libtest does. I would love to support a more full-featured machine-readable format, but that will require a fair bit of design and implementation work (see nextest [issue #20](https://github.com/nextest-rs/nextest/issues/20)). The work isn't on my employer's radar so I don't expect to get to it, but if you'd like to help out (even by just commenting there about what your needs are) it would be really helpful!

**Comment by Canop** [comment]
Hello @sunshowers, thanks for coming here!

I suppose we'll try to see what we manage to obtain with the `libtest-json` format, or maybe the `libtest-json-plus` one.

Regarding the human-readable format, bacon doesn't need a lot of stability, just the ability to [recognize a few line types](https://github.com/Canop/bacon/blob/main/src/analysis/nextest/nextest_line_analyser.rs) which should be easy as we can rely on  styling which is unlikely to appear otherwise. We'd just need, for each specific kind of line (location, start of stderr, etc.) a frozen ansi escape sequence and a basic shape.

If I'm unclear, an input line for bacon is an array of (`csi`, `raw`) strings, and recognizing a line is usually something like this:

```rust
const CSI_LINE_COL: &str = "\u{1b}[2m";
const CSI_ERROR: &str = "\u{1b}[31m";

/// Return true when the line is like
///    "67:52  error  Unnecessary escape character: \/  no-useless-escape"
fn is_line_col_error_line(content: &TLine) -> bool {
    let mut strings = content.strings.iter();
    let (Some(first), Some(second), Some(third), Some(fourth)) = (
        strings.next(),
        strings.next(),
        strings.next(),
        strings.next(),
    ) else {
        return false;
    };
    first.is_blank()
        && second.csi == CSI_LINE_COL
        && regex_is_match!(r"^\d+:\d+$", &second.raw)
        && third.is_blank()
        && fourth.csi == CSI_ERROR
        && fourth.raw == "error"
}
```

**Comment by sunshowers** [comment]
> Regarding the human-readable format, bacon doesn't need a lot of stability, just the ability to [recognize a few line types](https://github.com/Canop/bacon/blob/main/src/analysis/nextest/nextest_line_analyser.rs) which should be easy as we can rely on styling which is unlikely to appear otherwise. We'd just need, for each specific kind of line (location, start of stderr, etc.) a frozen ansi escape sequence and a basic shape.

Ah gotcha. So I guess the change that broke you was the one where we started producing Unicode characters.

**Comment by Canop** [comment]
@fredrik-jansson-se While there's no complete solution based on nextest's JSON output, I modified in PR #285 the previous analyzer

@sunshowers Please have a look at PR #285. I could modify the analyzer to support both versions. I think you might be able to define sequences of (csi, patterns) that have a low probability of changing (and if they change and there's an issue in bacon before the new version of nextest is released, this can be managed).

**Comment by fredrik-jansson-se** [comment]
@Canop, sounds good! I didn’t get unstuck, so if you have a solution, please go with that. I’m afk for a couple of days for Xmas. 

Happy holidays!

**Comment by Canop** [comment]
I'll merge my PR, even if it's far from perfect, in order to relieve the problem for nextest users.
